name: Pdoc

'on':
  push:
    branches:
      - main

jobs:
  check-build:
    name: Check docs build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.1.3
      - name: run pdoc
        run: |
          poetry install
          ./docs/build.sh

  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.1.3
      - name: Build docs
        run: |
          poetry install
          ./docs/build.sh
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Publish Docs
        run: |
          git config --global user.email "Github Actions"
          git config --global user.name "actions@magpie.dev"
          git remote set-url origin https://${{ secrets.USERNAME }}:${{ secrets.PASSWORD }}@github.com/magpie-dev/hikari-crescent.git
          npm install gh-pages
          node docs/publish.js
